name:
version: 0.0.1
build: 1
encrypt stacks: false
multiple instances: false
relaunch in background: false
shutdown when all windows are closed: false
creator code:
application data folder:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
preferences filename:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
ui:
  1:
    folder: ./ui
libraries:
  1:
    folder: ./libraries
frontscripts:
  1:
    folder: ./frontscripts
backscripts:
  1:
    folder: ./backscripts
helpers:
  1:
    folder: ./helpers
  2:
    filename: {{FRAMEWORK}}/helpers/preferences
behaviors:
  1:
    folder: ./behaviors
build folder: ../builds
build profiles:
  all profiles:
    post build script:
    certificates:
      macos:
        name:
    copy files:
      all platforms:
        1:
          filename: assets
      macos:
      windows:
      linux:
      ios:
      android:
  release:
  beta:
